##
images = ["images/lawless-logo.png"]
description = "Lawless RW provides rehabilitative restoration and waterproofing, concrete preparation, water jetting, and facade maintenance services."
keywords = "Construction, waterproofing, concrete preparation, water jetting, facade maintenance"
title = "Lawless Restoration & Waterproofing"

## Theme Params
bgImgSize = "2080x"
phone = "1 (781) 797 0404"
address1 = "3 Bessom St, Suite 112"
address2 = "Marblehead, MA 01945"
email = "info@lawlessrw.com"
linkedin = "[LinkedIn](https://www.linkedin.com/in/steven-dowdy-62929991/)"
copyright = "&#169; Lawless Restoration & Waterproofing, LLC"
design = "Site design by [Coto.Studio](https://coto.studio) ðŸ‡¸ðŸ‡»"

[[themeColor]]
  schema = "light"
  content = "#ffffff"
  #customMedia = ""
[[themeColor]]
  schema = "dark"
  content = "#000000"